export enum MESSAGE_EVENT {
  'SEEN_MESSAGE_CONVERSATION_SSC' = 'SEND_MESSAGE_CONVERSATION_SSC',
  'SEEN_MESSAGE_CONVERSATION_CSS' = 'SEND_MESSAGE_CONVERSATION_CSS',
  'JOIN_CONVERSATION_SSC' = 'JOIN_CONVERSATION_SSC',
  'JOIN_CONVERSATION_CSS' = 'JOIN_CONVERSATION_CSS',
  'LEAVE_CONVERSATION_SSC' = 'LEAVE_CONVERSATION_SSC',
  'LEAVE_CONVERSATION_CSS' = 'LEAVE_CONVERSATION_CSS',
}
